name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Docker image
        run: docker build -t ai-query-backend .
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/ai-query-backend:latest
      - name: Deploy to Kubernetes cluster
        uses: kubernetes/kubectl-action@v1
        with:
          # Replace with your actual Kubernetes config file
          config-file: ./config/kubernetes/config.yaml 
          command: apply
          arguments: -f ./k8s/deployment.yaml